from stock_data_tools import last_train_data,deleteNullFile,delet,init,compare_date
import os
import pandas as pd
from multiprocessing import Pool,Lock
from utils.path_and_canshu import basic_data_save_path,other_file_path,参数化数据,周期转化后
import talib  
import numpy as np
def 参数生成_all(path,goal_path,multiprocess=True):
    '''
    其他参数
    :path:数据源的地址
    :goal_path:目标储存位置
    '''
    if 'SZ000001.csv' not in os.listdir(goal_path) or pd.read_csv(goal_path+'SZ000001.csv',encoding='gb18030').shape[1]<30 or pd.read_csv(goal_path+'SZ000001.csv',encoding='gb18030')['交易日期'].iat[-1]!=last_train_data():
        delet(goal_path)
    codelist = os.listdir(path)
    for i in range(len(codelist)):
        if codelist[i] not in os.listdir(goal_path):
            codelist[i]=path+codelist[i]+','+goal_path
    if multiprocess:
        lock = Lock()
        pool = Pool(16, initializer=init, initargs=(lock,))
        pool.map_async(参数生成,codelist)
        pool.close()
        pool.join()
    else:
        for i in codelist:
            参数生成(i)
    # 参数生成(codelist[0])
    print('参数化完成')
def 参数生成(filename):
    goal_path=filename.split(',')[1]
    filename=filename.split(',')[0]
    df=pd.read_csv(filename,encoding='gb18030')
    # rename_dict={'开盘价':'open','收盘价':'close','最高价':'high','最低价':'low','成交量':'volume','成交额（千元）':'amount'}
    # df.rename(columns=rename_dict,inplace=True)
    # df['复权涨跌幅']=df['收盘价']/df['收盘价'].shift(1)-1
    df['CDL2CROWS'] = talib.CDL2CROWS(df['开盘价'], df['最高价'], df['最低价'], df['收盘价'])
    df['CDL3BLACKCROWS'] = talib.CDL3BLACKCROWS(df['开盘价'], df['最高价'], df['最低价'], df['收盘价'])
    df['CDL3INSIDE'] = talib.CDL3INSIDE(df['开盘价'], df['最高价'], df['最低价'], df['收盘价'])
    df['CDL3LINESTRIKE'] = talib.CDL3LINESTRIKE(df['开盘价'], df['最高价'], df['最低价'], df['收盘价'])
    df['CDL3OUTSIDE'] = talib.CDL3OUTSIDE(df['开盘价'], df['最高价'], df['最低价'], df['收盘价'])
    df['CDL3STARSINSOUTH'] = talib.CDL3STARSINSOUTH(df['开盘价'], df['最高价'], df['最低价'], df['收盘价'])
    df['CDL3WHITESOLDIERS'] = talib.CDL3WHITESOLDIERS(df['开盘价'], df['最高价'], df['最低价'], df['收盘价'])
    df['CDLABANDONEDBABY'] = talib.CDLABANDONEDBABY(df['开盘价'], df['最高价'], df['最低价'], df['收盘价'], penetration=0)
    df['CDLADVANCEBLOCK'] = talib.CDLADVANCEBLOCK(df['开盘价'], df['最高价'], df['最低价'], df['收盘价'])
    df['CDLBELTHOLD'] = talib.CDLBELTHOLD(df['开盘价'], df['最高价'], df['最低价'], df['收盘价'])
    df['CDLBREAKAWAY'] = talib.CDLBREAKAWAY(df['开盘价'], df['最高价'], df['最低价'], df['收盘价'])
    df['CDLCLOSINGMARUBOZU'] = talib.CDLCLOSINGMARUBOZU(df['开盘价'], df['最高价'], df['最低价'], df['收盘价'])
    df['CDLCONCEALBABYSWALL'] = talib.CDLCONCEALBABYSWALL(df['开盘价'], df['最高价'], df['最低价'], df['收盘价'])
    df['CDLCOUNTERATTACK'] = talib.CDLCOUNTERATTACK(df['开盘价'], df['最高价'], df['最低价'], df['收盘价'])
    df['CDLDARKCLOUDCOVER'] = talib.CDLDARKCLOUDCOVER(df['开盘价'], df['最高价'], df['最低价'], df['收盘价'], penetration=0)
    df['CDLDOJI'] = talib.CDLDOJI(df['开盘价'], df['最高价'], df['最低价'], df['收盘价'])
    df['CDLDOJISTAR'] = talib.CDLDOJISTAR(df['开盘价'], df['最高价'], df['最低价'], df['收盘价'])
    df['CDLDRAGONFLYDOJI'] = talib.CDLDRAGONFLYDOJI(df['开盘价'], df['最高价'], df['最低价'], df['收盘价'])
    df['CDLENGULFING'] = talib.CDLENGULFING(df['开盘价'], df['最高价'], df['最低价'], df['收盘价'])
    df['CDLEVENINGDOJISTAR'] = talib.CDLEVENINGDOJISTAR(df['开盘价'], df['最高价'], df['最低价'], df['收盘价'], penetration=0)
    df['CDLEVENINGSTAR'] = talib.CDLEVENINGSTAR(df['开盘价'], df['最高价'], df['最低价'], df['收盘价'], penetration=0)
    df['CDLGAPSIDESIDEWHITE'] = talib.CDLGAPSIDESIDEWHITE(df['开盘价'], df['最高价'], df['最低价'], df['收盘价'])
    df['CDLGRAVESTONEDOJI'] = talib.CDLGRAVESTONEDOJI(df['开盘价'], df['最高价'], df['最低价'], df['收盘价'])
    df['CDLHAMMER'] = talib.CDLHAMMER(df['开盘价'], df['最高价'], df['最低价'], df['收盘价'])
    df['CDLHANGINGMAN'] = talib.CDLHANGINGMAN(df['开盘价'], df['最高价'], df['最低价'], df['收盘价'])
    df['CDLHARAMI'] = talib.CDLHARAMI(df['开盘价'], df['最高价'], df['最低价'], df['收盘价'])
    df['CDLHARAMICROSS'] = talib.CDLHARAMICROSS(df['开盘价'], df['最高价'], df['最低价'], df['收盘价'])
    df['CDLHIGHWAVE'] = talib.CDLHIGHWAVE(df['开盘价'], df['最高价'], df['最低价'], df['收盘价'])
    df['CDLHIKKAKE'] = talib.CDLHIKKAKE(df['开盘价'], df['最高价'], df['最低价'], df['收盘价'])
    df['CDLHIKKAKEMOD'] = talib.CDLHIKKAKEMOD(df['开盘价'], df['最高价'], df['最低价'], df['收盘价'])
    df['CDLHOMINGPIGEON'] = talib.CDLHOMINGPIGEON(df['开盘价'], df['最高价'], df['最低价'], df['收盘价'])
    df['CDLIDENTICAL3CROWS'] = talib.CDLIDENTICAL3CROWS(df['开盘价'], df['最高价'], df['最低价'], df['收盘价'])
    df['CDLINNECK'] = talib.CDLINNECK(df['开盘价'], df['最高价'], df['最低价'], df['收盘价'])
    df['CDLINVERTEDHAMMER'] = talib.CDLINVERTEDHAMMER(df['开盘价'], df['最高价'], df['最低价'], df['收盘价'])
    df['CDLKICKING'] = talib.CDLKICKING(df['开盘价'], df['最高价'], df['最低价'], df['收盘价'])
    df['CDLKICKINGBYLENGTH'] = talib.CDLKICKINGBYLENGTH(df['开盘价'], df['最高价'], df['最低价'], df['收盘价'])
    df['CDLLADDERBOTTOM'] = talib.CDLLADDERBOTTOM(df['开盘价'], df['最高价'], df['最低价'], df['收盘价'])
    df['CDLLONGLEGGEDDOJI'] = talib.CDLLONGLEGGEDDOJI(df['开盘价'], df['最高价'], df['最低价'], df['收盘价'])
    df['CDLLONGLINE'] = talib.CDLLONGLINE(df['开盘价'], df['最高价'], df['最低价'], df['收盘价'])
    df['CDLMARUBOZU'] = talib.CDLMARUBOZU(df['开盘价'], df['最高价'], df['最低价'], df['收盘价'])
    df['CDLMATCHINGLOW'] = talib.CDLMATCHINGLOW(df['开盘价'], df['最高价'], df['最低价'], df['收盘价'])
    df['CDLMATHOLD'] = talib.CDLMATHOLD(df['开盘价'], df['最高价'], df['最低价'], df['收盘价'], penetration=0)
    df['CDLMORNINGDOJISTAR'] = talib.CDLMORNINGDOJISTAR(df['开盘价'], df['最高价'], df['最低价'], df['收盘价'], penetration=0)
    df['CDLMORNINGSTAR'] = talib.CDLMORNINGSTAR(df['开盘价'], df['最高价'], df['最低价'], df['收盘价'], penetration=0)
    df['CDLONNECK'] = talib.CDLONNECK(df['开盘价'], df['最高价'], df['最低价'], df['收盘价'])
    df['CDLPIERCING'] = talib.CDLPIERCING(df['开盘价'], df['最高价'], df['最低价'], df['收盘价'])
    df['CDLRICKSHAWMAN'] = talib.CDLRICKSHAWMAN(df['开盘价'], df['最高价'], df['最低价'], df['收盘价'])
    df['CDLRISEFALL3METHODS'] = talib.CDLRISEFALL3METHODS(df['开盘价'], df['最高价'], df['最低价'], df['收盘价'])
    df['CDLSEPARATINGLINES'] = talib.CDLSEPARATINGLINES(df['开盘价'], df['最高价'], df['最低价'], df['收盘价'])
    df['CDLSHOOTINGSTAR'] = talib.CDLSHOOTINGSTAR(df['开盘价'], df['最高价'], df['最低价'], df['收盘价'])
    df['CDLSHORTLINE'] = talib.CDLSHORTLINE(df['开盘价'], df['最高价'], df['最低价'], df['收盘价'])
    df['CDLSPINNINGTOP'] = talib.CDLSPINNINGTOP(df['开盘价'], df['最高价'], df['最低价'], df['收盘价'])
    df['CDLSTALLEDPATTERN'] = talib.CDLSTALLEDPATTERN(df['开盘价'], df['最高价'], df['最低价'], df['收盘价'])
    df['CDLSTICKSANDWICH'] = talib.CDLSTICKSANDWICH(df['开盘价'], df['最高价'], df['最低价'], df['收盘价'])
    df['CDLTAKURI'] = talib.CDLTAKURI(df['开盘价'], df['最高价'], df['最低价'], df['收盘价'])
    df['CDLTASUKIGAP'] = talib.CDLTASUKIGAP(df['开盘价'], df['最高价'], df['最低价'], df['收盘价'])
    df['CDLTHRUSTING'] = talib.CDLTHRUSTING(df['开盘价'], df['最高价'], df['最低价'], df['收盘价'])
    df['CDLTRISTAR'] = talib.CDLTRISTAR(df['开盘价'], df['最高价'], df['最低价'], df['收盘价'])
    df['CDLUNIQUE3RIVER'] = talib.CDLUNIQUE3RIVER(df['开盘价'], df['最高价'], df['最低价'], df['收盘价'])
    df['CDLUPSIDEGAP2CROWS'] = talib.CDLUPSIDEGAP2CROWS(df['开盘价'], df['最高价'], df['最低价'], df['收盘价'])

    df['DEMA'] = talib.DEMA(df['收盘价'], timeperiod=30)
    df['EMA'] = talib.EMA(df['收盘价'], timeperiod=30)
    df['HT_TRENDLINE'] = talib.HT_TRENDLINE(df['收盘价'])
    df['KAMA'] = talib.KAMA(df['收盘价'], timeperiod=30)
    df['MA'] = talib.MA(df['收盘价'], timeperiod=30, matype=0)
    # df['MAVP'] = talib.MAVP(df['收盘价'])
    df['MIDPOINT'] = talib.MIDPOINT(df['收盘价'], timeperiod=14)
    df['MIDPRICE'] = talib.MIDPRICE(df['最高价'], df['最低价'], timeperiod=14)
    df['SAR'] = talib.SAR(df['最高价'], df['最低价'])
    df['SAREXT'] = talib.SAREXT(df['最高价'], df['最低价'])
    df['SMA'] = talib.SMA(df['收盘价'], timeperiod=30)
    df['T3'] = talib.T3(df['收盘价'], timeperiod=5, vfactor=0)
    df['TEMA'] = talib.TEMA(df['收盘价'], timeperiod=30)
    df['TRIMA'] = talib.TRIMA(df['收盘价'], timeperiod=30)
    df['WMA'] = talib.WMA(df['收盘价'], timeperiod=30)
    df['ADX'] = talib.ADX(df['最高价'], df['最低价'], df['收盘价'], timeperiod=14)
    df['ADXR'] = talib.ADXR(df['最高价'], df['最低价'], df['收盘价'], timeperiod=14)
    df['APO'] = talib.APO(df['收盘价'], fastperiod=12, slowperiod=26, matype=0)
    df['AROONOSC'] = talib.AROONOSC(df['最高价'], df['最低价'], timeperiod=14)
    df['BOP'] = talib.BOP(df['开盘价'], df['最高价'], df['最低价'], df['收盘价'])
    df['CCI'] = talib.CCI(df['最高价'], df['最低价'], df['收盘价'], timeperiod=14)
    df['CMO'] = talib.CMO(df['收盘价'], timeperiod=14)
    df['DX'] = talib.DX(df['最高价'], df['最低价'], df['收盘价'], timeperiod=14)
    df['MACDmacdhist'],df['MACDmacdsignal'],df['MACDmacd'] = talib.MACD(df['收盘价'], fastperiod=12, slowperiod=26, signalperiod=9)
    df['MACDEXTmacdhist'],df['MACDEXTmacdsignal'],df['MACDEXTmacd'] = talib.MACDEXT(df['收盘价'], fastperiod=12, fastmatype=0, slowperiod=26, slowmatype=0, signalperiod=9, signalmatype=0)
    df['MACDFIXmacdhist'],df['MACDFIXmacdsignal'],df['MACDFIXmacd'] = talib.MACDFIX(df['收盘价'], signalperiod=9)
    df['MFI'] = talib.MFI(df['最高价'], df['最低价'], df['收盘价'], df['成交量'], timeperiod=14)
    df['MINUS_DI'] = talib.MINUS_DI(df['最高价'], df['最低价'], df['收盘价'], timeperiod=14)
    df['MINUS_DM'] = talib.MINUS_DM(df['最高价'], df['最低价'], timeperiod=14)
    df['MOM'] = talib.MOM(df['收盘价'], timeperiod=10)
    df['PLUS_DI'] = talib.PLUS_DI(df['最高价'], df['最低价'], df['收盘价'], timeperiod=14)
    df['PLUS_DM'] = talib.PLUS_DM(df['最高价'], df['最低价'], timeperiod=14)
    df['PPO'] = talib.PPO(df['收盘价'], fastperiod=12, slowperiod=26, matype=0)
    df['ROC'] = talib.ROC(df['收盘价'], timeperiod=10)
    df['ROCP'] = talib.ROCP(df['收盘价'], timeperiod=10)
    df['ROCR'] = talib.ROCR(df['收盘价'], timeperiod=10)
    df['ROCR100'] = talib.ROCR100(df['收盘价'], timeperiod=10)
    df['RSI'] = talib.RSI(df['收盘价'], timeperiod=14)
    df['TRIX'] = talib.TRIX(df['收盘价'], timeperiod=30)
    df['ULTOSC'] = talib.ULTOSC(df['最高价'], df['最低价'], df['收盘价'], timeperiod1=7, timeperiod2=14, timeperiod3=28)
    df['WILLR'] = talib.WILLR(df['最高价'], df['最低价'], df['收盘价'], timeperiod=14)
    df['AD'] = talib.AD(df['最高价'], df['最低价'], df['收盘价'], df['成交量'])
    df['ADOSC'] = talib.ADOSC(df['最高价'], df['最低价'], df['收盘价'], df['成交量'], fastperiod=3, slowperiod=10)
    df['OBV'] = talib.OBV(df['收盘价'], df['成交量'])
    df['ATR'] = talib.ATR(df['最高价'], df['最低价'], df['收盘价'], timeperiod=14)
    df['NATR'] = talib.NATR(df['最高价'], df['最低价'], df['收盘价'], timeperiod=14)
    df['TRANGE'] = talib.TRANGE(df['最高价'], df['最低价'], df['收盘价'])
    df['AVGPRICE'] = talib.AVGPRICE(df['开盘价'], df['最高价'], df['最低价'], df['收盘价'])
    df['MEDPRICE'] = talib.MEDPRICE(df['最高价'], df['最低价'])
    df['TYPPRICE'] = talib.TYPPRICE(df['最高价'], df['最低价'], df['收盘价'])
    df['WCLPRICE'] = talib.WCLPRICE(df['最高价'], df['最低价'], df['收盘价'])
    df['HT_DCPERIOD'] = talib.HT_DCPERIOD(df['收盘价'])
    df['HT_DCPHASE'] = talib.HT_DCPHASE(df['收盘价'])
    df['HT_PHASORquadrature'],df['HT_PHASORinphase'] = talib.HT_PHASOR(df['收盘价'])
    df['HT_SINEleadsine'],df['HT_SINEsine'] = talib.HT_SINE(df['收盘价'])
    df['STOCHslowd'],df['STOCHslowk'] = talib.STOCH(df['最高价'], df['最低价'], df['收盘价'], fastk_period=5, slowk_period=3, slowk_matype=0, slowd_period=3, slowd_matype=0)
    df['STOCHFfastd'],df['STOCHFfastk'] = talib.STOCHF(df['最高价'], df['最低价'], df['收盘价'], fastk_period=5, fastd_period=3, fastd_matype=0)
    df['STOCHRSIfastd'],df['STOCHRSIfastk'] = talib.STOCHRSI(df['收盘价'], timeperiod=14, fastk_period=5, fastd_period=3, fastd_matype=0)
    df['AROONaroonup'],df['AROONaroondown'] = talib.AROON(df['最高价'], df['最低价'], timeperiod=14)
    # df['MAMAfama'],df['MAMAmama'] = talib.MAMA(df['收盘价'], fastlimit=3, slowlimit=5)
    df['BBANDSlowerband'],df['BBANDSmiddleband'],df['BBANDSupperband'] = talib.BBANDS(df['收盘价'], timeperiod=5, nbdevup=2, nbdevdn=2, matype=0) #stock.drop(changeratelist,axis=1,inplace=True)
    df['BETA'] = talib.BETA(df['最高价'], df['最低价'], timeperiod=5)
    df['CORREL'] = talib.CORREL(df['最高价'], df['最低价'], timeperiod=30)
    df['LINEARREG'] = talib.LINEARREG(df['收盘价'], timeperiod=14)
    df['LINEARREG_ANGLE'] = talib.LINEARREG_ANGLE(df['收盘价'], timeperiod=14)
    df['LINEARREG_INTERCEPT'] = talib.LINEARREG_INTERCEPT(df['收盘价'], timeperiod=14)
    df['LINEARREG_SLOPE'] = talib.LINEARREG_SLOPE(df['收盘价'], timeperiod=14)
    df['STDDEV'] = talib.STDDEV(df['收盘价'], timeperiod=5, nbdev=1)
    df['TSF'] = talib.TSF(df['收盘价'], timeperiod=14)
    df['VAR'] = talib.VAR(df['收盘价'], timeperiod=5, nbdev=1)
    df.replace(float('inf'),0,inplace=True)
    df.replace(float('-inf'),0,inplace=True)
    drop_columns=['CDLHOMINGPIGEON_-2s','VAR_-1s','VAR_-2s','LINEARREG_SLOPE_-1s','LINEARREG_SLOPE_-2s','LINEARREG_ANGLE_-1s','LINEARREG_ANGLE_-2s','BETA_-1s','BETA_-2s','STOCHRSIfastd_-1s','STOCHRSIfastd_-2s','STOCHslowk_-1s','STOCHslowk_-2s','HT_PHASORquadrature_-1s','HT_PHASORquadrature_-2s','ADOSC_-1s','ADOSC_-2s','ULTOSC_-1s','ULTOSC_-2s','PPO_-1s','PPO_-2s','MFI_-1s','MFI_-2s','MACDEXTmacdhist_-1s','MACDEXTmacdhist_-2s','MACDEXTmacdsignal_-1s','MACDEXTmacdsignal_-2s','MACDEXTmacd_-1s','MACDEXTmacd_-2s','CCI_-1s','CCI_-2s','APO_-1s','APO_-2s','CDLTRISTAR_-1s','CDLTRISTAR_-2s','CDLUNIQUE3RIVER_-1s','CDLUNIQUE3RIVER_-2s','CDLUPSIDEGAP2CROWS_-1s','CDLUPSIDEGAP2CROWS_-2s','CDLTASUKIGAP_-1s','CDLTASUKIGAP_-2s','CDLSTICKSANDWICH_-1s','CDLSTICKSANDWICH_-2s','CDLRISEFALL3METHODS_-1s','CDLRISEFALL3METHODS_-2s','CDLSEPARATINGLINES_-1s','CDLSEPARATINGLINES_-2s','CDLMORNINGSTAR_-2s','CDLONNECK_-1s','CDLONNECK_-2s','CDLMATCHINGLOW_-2s','CDLMATHOLD_-1s','CDLMATHOLD_-2s','CDLMORNINGDOJISTAR_-1s','CDLMORNINGDOJISTAR_-2s','CDLKICKING_-1s','CDLKICKING_-2s','CDLKICKINGBYLENGTH_-1s','CDLKICKINGBYLENGTH_-2s','CDLLADDERBOTTOM_-1s','CDLLADDERBOTTOM_-2s','CDLINNECK_-2s','CDLIDENTICAL3CROWS_-1s','CDLIDENTICAL3CROWS_-2s','CDLHIKKAKEMOD_-1s','CDLHIKKAKEMOD_-2s','CDLGAPSIDESIDEWHITE_-1s','CDLGAPSIDESIDEWHITE_-2s','CDLEVENINGDOJISTAR_-1s','CDLCONCEALBABYSWALL_-1s','CDLCONCEALBABYSWALL_-2s','CDLCOUNTERATTACK_-1s','CDLCOUNTERATTACK_-2s','CDLBREAKAWAY_-1s','CDLBREAKAWAY_-2s','CDL3STARSINSOUTH_-1s','CDL3STARSINSOUTH_-2s','CDL3WHITESOLDIERS_-1s','CDL3WHITESOLDIERS_-2s','CDLABANDONEDBABY_-1s','CDLABANDONEDBABY_-2s','CDL3LINESTRIKE_-1s','CDL3LINESTRIKE_-2s','CDL3BLACKCROWS_-1s','CDL3BLACKCROWS_-2s','MOM','CDLUPSIDEGAP2CROWS','CDLTRISTAR','CDLTASUKIGAP','CDLSTICKSANDWICH','CDLRISEFALL3METHODS','CDLSEPARATINGLINES','CDLONNECK','CDLMATHOLD','CDLMORNINGDOJISTAR','CDLKICKING','CDLKICKINGBYLENGTH','CDLLADDERBOTTOM','CDLIDENTICAL3CROWS','CDLHIKKAKEMOD','CDLGAPSIDESIDEWHITE','CDLEVENINGDOJISTAR','CDLCONCEALBABYSWALL','CDLCOUNTERATTACK','CDLBREAKAWAY','CDL3STARSINSOUTH','CDL3WHITESOLDIERS','CDLABANDONEDBABY','CDL3LINESTRIKE','CDL2CROWS','CDL3BLACKCROWS','CDL3INSIDE','CDLEVENINGSTAR','CDLINNECK','CDLSTALLEDPATTERN','CDLUNIQUE3RIVER','CDL3INSIDE_-1s','CDLADVANCEBLOCK_-2s','CDLDRAGONFLYDOJI_-2s','CDLEVENINGDOJISTAR_-2s','CDLEVENINGSTAR_-1s','CDLEVENINGSTAR_-2s','CDLGRAVESTONEDOJI_-1s','CDLGRAVESTONEDOJI_-2s','CDLMATCHINGLOW_-1s','CDLMORNINGSTAR_-1s','CDLPIERCING_-1s','CDLPIERCING_-2s','CDLSHOOTINGSTAR_-1s','CDLSHOOTINGSTAR_-2s','CDLSTALLEDPATTERN_-1s','CDLSTALLEDPATTERN_-2s','CDLTAKURI_-1s','STOCHslowd_-1s','STOCHslowd_-2s','STOCHFfastk_-1s','STOCHFfastk_-2s']
    drop_columns=['MOM','CDLUPSIDEGAP2CROWS','CDLTRISTAR','CDLTASUKIGAP','CDLSTICKSANDWICH','CDLRISEFALL3METHODS','CDLSEPARATINGLINES','CDLONNECK','CDLMATHOLD','CDLMORNINGDOJISTAR','CDLKICKING','CDLKICKINGBYLENGTH','CDLLADDERBOTTOM','CDLIDENTICAL3CROWS','CDLHIKKAKEMOD','CDLGAPSIDESIDEWHITE','CDLEVENINGDOJISTAR','CDLCONCEALBABYSWALL','CDLCOUNTERATTACK','CDLBREAKAWAY','CDL3STARSINSOUTH','CDL3WHITESOLDIERS','CDLABANDONEDBABY','CDL3LINESTRIKE','CDL2CROWS','CDL3BLACKCROWS','CDL3INSIDE','CDLEVENINGSTAR','CDLINNECK','CDLSTALLEDPATTERN','CDLUNIQUE3RIVER']
    # df.to_csv(goal_path+filename.split('\\')[-1],encoding='gb18030',index=None,float_format='%.4f')
    # for i in range(len(averagelist)):
    #     stock[str(list(stock.columns)[averagelist[i]])] =stock[str(list(stock.columns)[averagelist[i]])]/stock['收盘价']  #stock.apply(lambda x: x[str(list(stock.columns)[averagelist[i]-1])] / x['close'], axis=1)
    # for i in changeratelist:
    #     k=stock[i].shift(1)
    #     k.drop([stock.index[0]],inplace=True)
    #     stock.drop([stock.index[0]],inplace=True)
        # stock[i+'_rate'] =(stock[i]-k)/k #stock.apply(lambda x: x[str(list(stock.columns)[averagelist[i]-1])] / x['close'], axis=1)
    # stock.drop(changeratelist,axis=1,inplace=True)
    # stock.replace(float('inf'),0,inplace=True)
    # stock.replace(float('-inf'),0,inplace=True)
    for i in range(9,len(df.columns)):
        df.iloc[:,i:i+1]=df.iloc[:,i:i+1]/(np.sum(df.iloc[:,i:i+1])/len(df))
        # df.iloc[:,i:i+1]=df.iloc[:,i:i+1]/df['收盘价']
        # df[list(df.columns)[i]+'_-1s']=(df.iloc[:,i:i+1]-df.iloc[:,i:i+1].shift(1))/df.iloc[:,i:i+1].shift(1)
        # stock[list(stock.columns)[i]+'_-1s']=stock[list(stock.columns)[i]]-stock[list(stock.columns)[i]+'_-1']
        # df[list(df.columns)[i]+'_-2s']=(df.iloc[:,i:i+1]-df.iloc[:,i:i+1].shift(2))/df.iloc[:,i:i+1].shift(2)
        # stock[list(stock.columns)[i]+'_-2s']=stock[list(stock.columns)[i]]-stock[list(stock.columns)[i]+'_-2']
    # df['复权涨跌幅']=(df['收盘价']-df['收盘价'].shift(1))/df['收盘价'].shift(1)
    df.drop(drop_columns,axis=1,inplace=True)
    df.replace(float('inf'),0,inplace=True)
    df.replace(float('-inf'),0,inplace=True)
    df=df.fillna(0)
    df.replace('None',0,inplace=True)
    # rename_dict={'open':'开盘价_后复权','clsoe':'收盘价_后复权','high':'最高价_后复权','low':'最低价_后复权','volume':'成交量（手）','amount':'成交额（千元）','涨跌幅':'涨跌额','涨跌额':'涨跌幅'}
    # df.rename(columns=rename_dict,inplace=True)
    df=df[100:]
    # lock.acquire()
    if len(df)>400:
        df.to_csv(goal_path+filename.split('\\')[-1],encoding='gb18030',index=None,float_format='%.4f')
    # lock.release()
    return 0
if __name__ == '__main__':
    delet(参数化数据)
    参数生成_all(basic_data_save_path,参数化数据,True)